trigger:
  branches:
    include:
      - main  # This triggers the pipeline on changes to the 'main' branch

schedules:
  - cron: "*/5 * * * *"  # This triggers the pipeline every 5 minutes
    displayName: "Run every 5 minutes"
    branches:
      include:
        - main  # Ensures the schedule runs on the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # The VM image to use for the pipeline

jobs:
  - job: BuildAndRun
    displayName: 'Build and Run bgmi binary with bot.py'

    steps:
      # Step 1: Checkout the repository code
      - task: Checkout@1
        displayName: 'Checkout Repository'

      # Step 2: Install Python version
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true

      # Step 3: Install Python dependencies (if a requirements.txt exists)
      - script: |
          python -m pip install --upgrade pip
          pip install -r $(Build.SourcesDirectory)/requirements.txt  # Install dependencies from requirements.txt if exists
          pip show telebot  # Verify installation of telebot
        displayName: 'Install Python dependencies'

      # Step 4: Copy the bgmi binary to a directory
      - script: |
          mkdir -p /app/bin  # Create a directory to store the binary file
          cp $(Build.SourcesDirectory)/bgmi /app/bin/  # Ensure you specify the correct path to the bgmi binary
        displayName: 'Copy bgmi binary file'

      # Step 5: Make the bgmi binary executable using chmod +x
      - script: |
          chmod +x /app/bin/bgmi  # Make bgmi binary executable
        displayName: 'Make bgmi executable'

      # Step 6: Run the Python script bot.py using python3
      - script: |
          python3 $(Build.SourcesDirectory)/bot.py  # Run bot.py using python3
        displayName: 'Run bot.py script'
        
