version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Use a Docker image with Python pre-installed
    steps:
      - checkout  # Checks out the source code from the repository

      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install telebot  # Install Python dependencies if any

      - run:
          name: Run Python script
          command: |
            python bot.py  # Run the Python file

      - run:
          name: Make binary file executable
          command: |
            chmod +x bgmi # Make the binary executable

      - run:
          name: Run the binary file
          command: |
            ./bgmi # Run the binary file

workflows:
  version: 2
  build:
    jobs:
      - build  # The "build" job is run in this workflow
      
